Remove pytz as test dependency.
plone/plone.app.caching pull request #141
Opened 2024-06-19 13:12 UTC by thet

2024-06-19 13:12 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2024-06-19 13:14 UTC, thet commented
@jenkins-plone-org please run jobs

2024-06-21 04:58 UTC, davisagli approved these changes

2024-06-21 04:59 UTC, davisagli requested changes
Tests are failing with `AttributeError: 'datetime.timezone' object has no attribute 'localize'`

2025-02-12 14:33 UTC, mamico commented on plone/app/caching/tests/test_utils.py
>      now = tzinfo.localize(now)  # set tzinfo with correct DST offset
```suggestion
    now = now.astimezone(tzinfo)  # set tzinfo with correct DST offset
```

@thet @davisagli this should, in my opinion, fix the tests here

2025-02-12 18:11 UTC, davisagli commented on plone/app/caching/tests/test_utils.py
>      now = tzinfo.localize(now)  # set tzinfo with correct DST offset
@mamico The suggestion makes sense (the localize method is unique to tzinfo from pytz).

But, a 1-hour offset for Europe/Vienna is only correct when summer time is not active. Does it matter here?

2025-02-16 22:22 UTC, davisagli commented on plone/app/caching/tests/test_utils.py
>      now = tzinfo.localize(now)  # set tzinfo with correct DST offset
I suggest creating a new branch of plone.app.caching to be used by Plone 6.0 and 6.1, and then make this change to use zoneinfo on the master branch (for Plone 6.2)

2026-03-22 17:18 UTC, thet commented on plone/app/caching/tests/test_utils.py
>      now = tzinfo.localize(now)  # set tzinfo with correct DST offset
@davisagli @mamico tnx for reviewing. I forgot about this PR and just saw these comments now.
I have fixe it now!

2026-03-22 18:42 UTC, davisagli approved these changes

2026-03-22 23:23 UTC, mamico approved these changes

2026-03-23 13:15 UTC, mauritsvanrees approved these changes

2026-03-23 13:15 UTC, merged

2026-03-23 13:15 UTC, mauritsvanrees commented
Merged.  Thanks!